INSERT INTO queueworkers (worker) VALUES ('broend-sync');
INSERT INTO queueworkers (worker) VALUES ('solr-sync');
INSERT INTO queueworkers (worker) VALUES ('basis-decentral');
INSERT INTO queueworkers (worker) VALUES ('solr-sync-bulk');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('opencataloging-update', 'broend-sync', 'A', 'Y');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('opencataloging-update', 'solr-sync', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('opencataloging-update', 'basis-decentral', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('bulk-broend', 'broend-sync', 'A', 'Y');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('bulk-solr', 'solr-sync-bulk', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('agency-delete', 'broend-sync', 'A', 'Y');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('agency-delete', 'solr-sync', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('agency-maintain', 'broend-sync', 'A', 'Y');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('agency-maintain', 'solr-sync', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('fbs-update', 'broend-sync', 'A', 'Y');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('fbs-update', 'solr-sync', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('fbs-update', 'basis-decentral', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('dataio-update', 'broend-sync', 'A', 'Y');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('dataio-update', 'solr-sync', 'Y', 'A');
INSERT INTO queueworkers (worker) VALUES ('ocb-test');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('dataio-update', 'ocb-test', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('opencataloging-update', 'ocb-test', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('fbs-ph-update', 'ocb-test', 'Y', 'A');
INSERT INTO queuerules (provider, worker, changed, leaf) VALUES ('dataio-ph-holding-update', 'ocb-test', 'Y', 'A');